export const NOTIFY_USER = "NOTIFY_USER";
export const DISABLED_BALANCE_ON_ADD = "DISABLED_BALANCE_ON_ADD";
export const DISABLED_BALANCE_ON_EDIT = "DISABLED_BALANCE_ON_EDIT";
export const ALLOW_REGISTRATION = "ALLOW_REGISTRATION";
